netflix:
  outputs:
    dev:
      dbname: netflix_data
      host: postgres
      pass: tarzangame
      port: 5432
      schema: DEV
      threads: 1
      type: postgres
      user: airflow
  target: dev
